language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install .
- python -c "import nltk; nltk.download('wordnet')"
script:
- pytest
notifications:
  slack:
    secure: nBn4qmb4OjcvD20FGlApggyNzWQmfzssMUifi7Pwa0f3+TUCUqdrG4PDadEsAuxVvqn5bUmA+gwpahl00mpf3h7XYOtTCQ+GjYsO0P78lzMD1Rb0iJHo/vRzxmLuWqT1eCLxDq9icatt/uC71FxsLHRQNP7JnsekLw31QlytTehkTQdtDT7ijYiKMY2g1HTDG3iP26tzQSoGK0QZ5dmuKU02ipsn3vAsEP5JiI5rCtmSqEqRbZIed680KTbfNXaKPCZEaXtMNtFN7WmrIRNviuDmqTRvot3u7zxQfGZ5AjBSy1yEo4D6WsvZRWzGhEZODNGTozIcrurn4DoyydkausU7ceowwGA+lAPpla7laU5kDtwU531ZvVWPRfTZT6FQ6G1mYCyxuKdQ1Li2vgmceS/7t0Ij4waP3VP+skXH68iBp6rVHOC+VSNO93I9341phpcyZdw8MdZUGmpvgnWu1VBXLE9FYjYn6IBQWbjuEodUjyBihVfTQGI1bAENXVFsolUQaYAVE021ZOtsw4e22dS4x8jx4BfUW9J1X6P+BO8egP4FiGqBpTyzIKuoKhWj2jxVwicsVd9xFEJJsw70x/Sgf0q5dlLfb1atx286uK7eguSIyYzIJEEqFqMfeHj19KYaDzhqHi591wfjso1LnjPI+ZD+7Zi9mUcTJLBe9Y4=
deploy:
  provider: pypi
  user: thesoulshell
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
    python: 3.6
  password:
    secure: C87nj0PBUaev9SHkvG8mCuv1FHGBI2SoAnsw0Z3W+WBxGBkb/vhNOZhVX/ZatrZfF+rHCnyt3EuTe777fBMoFGlYG3Z/Hu/vNNWvltx2cp+D2uFQoB5IQ4kjxbVCC6ZhCgCkBAvqnYfiWFVqg5bXB4GbAYd/SAudrjbRienfU5Y0wlcQTVWJs5uAsokgvSAFsZTzWO6qQgshwP6hbW4nQyMKLhGH/XqvgN1fTxH5qDbF/t9UK3T9VglUYkTFhIA3dsy2BiyopRr1vSR3uxoVFo7jCgUyXcjSjsw9FX0LrieDPkFPq89wo8XmCAon81cRmnjGzDzl/uptpy6smydVpG+an9UC+afQ36Gdiki3FoHsrCXOhW9sNAnMoOwUE/fE4Y/ksilODR0WyH2ofI7uxRhWyJ5wqZe/X2R5SwdeoC9iEvFgYAdTh7r+biKVjDkoGquFd+sDrzyUAbGRoQRCibnKaxeO82BHzXXP7mQP+wkotEOtCnRrzSykEgsKsxoGIA9Z0p53zQ7o4QynwPPhplV5p0glELhw5WFoF0irRIx3nk0ZBcA5LEla2qPl7JypqMiVxHe7qIvfbhsIukdcEY8SWs+r7KPj63jSHr4egPJcw0QoQq/Fd3Q+qMGMViPBcsU6VhV62xQWG8HrBhaRQmFhbMot9ieBFcrgJieBFYo=
